security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        josmanoa_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:    ^/
            access_denied_handler: App\Security\AccessDeniedHandler
            provider: josmanoa_provider
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                csrf_token_generator: security.csrf.token_manager
            guard:
                authenticators:
                    - "App\\Security\\AjaxAuthenticator"
            logout:
                path:   /logout
                target: /

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
        ROLE_USER: [ROLE_GUEST]


    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/media/create, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/album, role: ROLE_USER }
        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }